apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pirx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pirx
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
      - name: pirx-container
        image: flowworks-carlsolutions.azurecr.io/flowworks/pirx
        env:
        - name: KAFKA_BROKER
          value: "prodkafka1:9092,prodkafka2:9092,prodkafka3:9092"
        - name: DATASETS_PATH
          value: "/data"
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      imagePullSecrets:
        - name: regsecret
